/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART_1.h"
#include "Tx_1_aliases.h"
#include "Tx_1.h"
#include "Pin_LED_0_aliases.h"
#include "Pin_LED_0.h"
#include "Pin_LED_1_aliases.h"
#include "Pin_LED_1.h"
#include "isr_UART1_TX_BYTE_COMPLETE.h"
#include "isr_UART1_RX_BYTE_RECEIVED.h"
#include "High_Frequency_PWM_0.h"
#include "Clock_1.h"
#include "isr_High_Frequency_2000Hz.h"
#include "USBUART.h"
#include "USBUART_audio.h"
#include "USBUART_cdc.h"
#include "USBUART_hid.h"
#include "USBUART_midi.h"
#include "USBUART_pvt.h"
#include "USBUART_cydmac.h"
#include "USBUART_msc.h"
#include "Pin_LED_2_aliases.h"
#include "Pin_LED_2.h"
#include "Pin_LED_3_aliases.h"
#include "Pin_LED_3.h"
#include "High_Frequency_PWM_1.h"
#include "isr_High_Frequency_2001Hz.h"
#include "Startup_Release_Switch_aliases.h"
#include "Startup_Release_Switch.h"
#include "Timer_20KHz.h"
#include "isrTimer_20KHz_TC.h"
#include "Timer_48MHz.h"
#include "UART_1_IntClock.h"
#include "USBUART_Dm_aliases.h"
#include "USBUART_Dm.h"
#include "USBUART_Dp_aliases.h"
#include "USBUART_Dp.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

